version: "3.9"

services:
    api:
        image: ${DOCKER_REGISTRY-}api
        restart: always
        ports:
            - "1970:8080"
            - "1973:8081"
        build:
            context: .
            dockerfile: API/Dockerfile
        environment:
            # Asp Net Core
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            # Time Zone
            - TZ=America/Santiago
            # Idioma
            - LANG=es_CL.UTF-8
            - LANGUAGE=es_CL:es
            - LC_ALL=es_CL.UTF-8
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro